[versions]
minecraft     = "1.21.6"
parchment     = "1.21.4:2025.03.23"
fabric-loader = "0.16.14"
fabric-api    = "0.127.0+1.21.6"
permissions   = "0.4.0"
keybinds      = "0.1.15+1.21.6"

# Compatability dependencies
c2me          = "0.3.4+alpha.0.42+1.21.6"

# Plugins
fabric-loom   = "1.10-SNAPSHOT"
mod-publish   = "0.8.4"
explosion     = "0.1.0"

[libraries]
minecraft     = { module = "com.mojang:minecraft"              , version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader"        , version.ref = "fabric-loader" }
fabric-api    = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
permissions   = { module = "me.lucko:fabric-permissions-api"   , version.ref = "permissions" }
keybinds      = { module = "me.senseiwells:simple-keybinding-library", version.ref = "keybinds" }

# Compatability dependencies
c2me          = { module = "maven.modrinth:c2me-fabric", version.ref = "c2me" }

[plugins]
mod-publish   = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
fabric-loom   = { id = "fabric-loom"                    , version.ref = "fabric-loom" }
explosion     = { id = "lol.bai.explosion"              , version.ref = "explosion" }