name: Dev Build
on:
  push:
    branches: [ '*' ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 21
      - run: ./gradlew build --stacktrace --no-daemon
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts from ${{ github.sha }}
          path: versions/*/build/libs/
